Refactor reaction_network.py
shyamd/pymatgen pull request #20
Opened 2020-10-23 23:57 UTC by mjwen

## Summary

*  Moved all Reaction classes to `reaction.py`
* Refactored all `generate()` functions, the general idea is to create a helper function that handles the reactions for a molecule entry. 
* Reworked MoleculeEntry a bit and added two functions that's going to be used in atom mapping generation (not used now).

## Minors 

* For most parts, I just rearranged the code, but there is one or two places I deleted
```python
if charge not in families:
    families[charge] = dict()
```
which is already considered in the function `categorize()`.

IMO, all stuff related to `templates` and `families` can be put to a separate function, taking the extracted reactions as input. This should make the code more clean. I guess the undergrad working with Evan probably is going to do this. 

## TODO 

* `reaction.py` and `reaction_network.py` are not formatted for easy comparison. But, I find it could still be difficult to compare directly using the GitHub PR comparison tool. you may want to vimdiff to see the changes. We should begin to format our code for easier PR in the future. I personally prefer black, but others like yapf is totally fine. 

- [x] All existing tests pass.

2020-10-27 23:35 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +    # TODO (mjwen) remove mol_doc from __init__ and self.mol_doc (large dict).
These seem like small changes; could they be included in this PR?

2020-10-27 23:39 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +        molecule = mol_doc["molecule"]
If these basic features aren't present, then the function should fail. However, it's probably better to have a custom error type and error message than just letting a KeyError occur (the user may not know how to interpret that).

So, I'm envisioning something like:

`molecule = mol_doc.get("molecule")
if molecule is None:
    raise BadMoleculeEntryError("Molecule not present in molecule document!")`

or something like that.

2020-10-27 23:48 UTC, mjwen commented on pymatgen/entries/mol_entry.py
> +    # TODO (mjwen) remove mol_doc from __init__ and self.mol_doc (large dict).
The reason I did not do it is for backward compatibility. I would guess somebody are passing mol_doc to initialize this class. But self.mol_doc might be removed (highly possible nobody is using it).

2020-10-27 23:50 UTC, mjwen commented on pymatgen/entries/mol_entry.py
> +        molecule = mol_doc["molecule"]
Good suggestion, will do.

2020-10-27 23:58 UTC, espottesmith requested changes
Mostly looks good, but there are some small and easy changes that I think could and should be added before this gets merged in. Some things would be nice to add in the future but don't need to be added now (I think I've noted this in my comments, but please let me know if there's any confusion).

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +    # TODO (mjwen) probably rename it as bonds, since we are dealing with molecules
I think either works in general, but yes, in a class that isn't explicitly graph-focused, "bonds" probably makes more sense.

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +        return [tuple(sorted(e)) for e in self.graph.edges()]
Good change.

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +    def num_atoms(self) -> int:
Properties for "nelectrons" and "spin_multiplicity" would also be nice, but you certainly don't have to add them; those would be very easy.

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +    # TODO (mjwen) rename it as get_free_energy() to distinguish that this a function
Agree with this change; I'd say go with it.

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +    def get_fragments(self) -> Dict[Tuple[int, int], List[MoleculeGraph]]:
Couldn't this function use the Fragmenter class that already exists in pymatgen? Seems redundant.

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +            H1---C0---H2
I know you're doing ASCII art here, and your tools are limited, but this is a bit tough to read.

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +            "Free Energy (298.15 K) = {:.4f} eV".format(self.free_energy()),
Weird that we use Hartree, kcal / cal, and eV here... this isn't something you did, but now it's really bothering me. We ought to fix that.

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/entries/tests/test_mol_entry.py
> +class TestMolEntry:
Just out of interest, why are you not using unittest here?

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/entries/tests/test_mol_entry.py
> +from pymatgen import Molecule
I'm glad that we now have some tests for molecule entries, but it seems that the coverage is still weak and more test could/should be added. General rule - one function, one test (though for things like properties those can be combined).

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/reaction_network/reaction.py
> +__author__ = "Sam Blau, Hetal Patel, Xiaowei Xie, Evan Spotte-Smith"
If you did the refactoring, Mingjian, feel free to add yourself as an author. It's only fair!

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/reaction_network/reaction.py
> +        return families, templates
If there are functions that are identical between classes, it feels like those should be removed from the class, either being put into a parent class or just being a separate function entirely.

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/reaction_network/reaction_network.py
> +# Import everything used to be in this file but moved to reaction.py in case somebody
Yeah, not a huge deal for this PR, but eventually we'd probably just want to rewrite the tests.

2020-10-27 23:58 UTC, espottesmith commented on pymatgen/reaction_network/tests/test_reaction_network.py
> +    unittest.main()
I really don't understand why this is such a big deal, but add a newline to the end of the file so the linter doesn't get angry.

2020-10-28 00:01 UTC, espottesmith commented on pymatgen/entries/mol_entry.py
> +    # TODO (mjwen) remove mol_doc from __init__ and self.mol_doc (large dict).
Since you've provided another way to generate a MoleculeEntry from a mol_doc, I think you could go ahead and remove it now. Maybe we'll just give everyone a fair warning before we merge into stable?

2020-10-28 00:02 UTC, espottesmith commented
Oh! One other thing that didn't get into my review. I just merged in a PR by @kamronald, so you'll need to make sure those changes don't break/conflict with anything here. His changes are (almost) exclusively focused on the KMC stuff, so it shouldn't be hard.

2020-10-29 02:43 UTC, mjwen commented on pymatgen/entries/mol_entry.py
> +    # TODO (mjwen) remove mol_doc from __init__ and self.mol_doc (large dict).
Fair point. Done.

2020-10-29 03:47 UTC, mjwen commented on pymatgen/entries/mol_entry.py
> +            H1---C0---H2
Updated a bit.

2020-10-29 03:54 UTC, mjwen commented on pymatgen/entries/tests/test_mol_entry.py
> +class TestMolEntry:
pytest is very easy to understand, use, and maintain; basically all you need is an assert statement. Saw a few comparisons of pytest, nose, and unittest, and pytest is highly recommended. So, I chose pytest at the first place and even did not try nose and unittest. Ah, also, pytest can run unittest and nose test.

2020-10-29 03:55 UTC, mjwen commented on pymatgen/entries/tests/test_mol_entry.py
> +from pymatgen import Molecule
Most of them should be tested in tests for Molecule and MoleculeGraph. But, yes, we should add more.

2020-10-29 04:00 UTC, mjwen commented on pymatgen/entries/mol_entry.py
> +    # TODO (mjwen) remove mol_doc from __init__ and self.mol_doc (large dict).
Well, reverted. Many test files have mol_doc and thus the corresponding test fails if we remove mol_doc from the __init__ function. I will leave it as now and let's redo this when we rework the tests (some of them can be improved; some even use pickle files).

2020-10-29 04:04 UTC, mjwen commented on pymatgen/reaction_network/tests/test_reaction_network.py
> +    unittest.main()
`black` should do it automatically once we format the code, but now added a blank line.

2020-10-29 04:12 UTC, mjwen commented on pymatgen/reaction_network/reaction.py
> +        return families, templates
Good call. moved the simple for loop to the function generate().

2020-10-29 04:18 UTC, mjwen commented
> Oh! One other thing that didn't get into my review. I just merged in a PR by @kamronald, so you'll need to make sure those changes don't break/conflict with anything here. His changes are (almost) exclusively focused on the KMC stuff, so it shouldn't be hard.

Rebased. Also made a few minor tweaks.

2020-10-30 02:27 UTC, mjwen commented on pymatgen/entries/mol_entry.py
> +    def get_fragments(self) -> Dict[Tuple[int, int], List[MoleculeGraph]]:
Not really. Fragment accepts Molecule as input and create mol graphs using Babel NN. Here, we know the graph already.

2020-10-30 02:30 UTC, mjwen commented
@espottesmith Updated. The ball is in your court now.

2020-10-30 16:21 UTC, espottesmith approved these changes

2020-10-30 16:22 UTC, merged