Atom mapping
shyamd/pymatgen pull request #22
Opened 2020-10-30 23:22 UTC by mjwen

## Summary

- Add atom mapping for all elementary reactions types. 

Please review this after #21 is merged. In such, the codes are formatted the same way, and it should be easy to compare.

2020-11-01 17:24 UTC, espottesmith commented
Please resolve the merge conflicts before I review.

2020-11-02 17:07 UTC, espottesmith requested changes
Just a few changes, like removing the redundant MolGraph splitting function and moving your bucketing function from the tests to the reaction_network function.

The atom mapping stuff is great, though I am just slightly worried about the problem of multiple possible isomorphisms.

2020-11-02 17:07 UTC, espottesmith commented on pymatgen/reaction_network/reaction.py
> +        return subgraphs
There's already a way to do this in the MoleculeGraph class (see split_molecule_subgraphs). This function is pretty redundant and should probably be removed.

Also, even if this were to remain, I don't think this should be a nested function. Nested functions are for cases where you do the same thing multiple times in a function, but aren't going to do that thing elsewhere. This functionality of splitting a MoleculeGraph is generally useful, and so would deserve to be its own function.

2020-11-02 17:07 UTC, espottesmith commented on pymatgen/reaction_network/tests/test_reaction.py
>              if r.reactant == self.LiEC_entry:
Good catch. Of the two options that you present, I prefer making sure there's only one LiEC.

2020-11-02 17:07 UTC, espottesmith commented on pymatgen/reaction_network/tests/test_reaction.py
> +
This actually seems very useful. Maybe move to reaction_network.py and use this to build the RN.entries dictionary?

2020-11-08 21:10 UTC, mjwen commented on pymatgen/reaction_network/reaction.py
> +        #  self.entry_ids = {e.entry_id for e in self.reactants + self.products}
The test passed without any problem. I was concerned that this may affect somebody's code not tested in the unit test. Since we are making the big moves to merge to the new repo, I suppose this type of "small" changes should be fine. Made the changes.

2020-11-08 21:11 UTC, mjwen commented on pymatgen/reaction_network/reaction.py
> +        self.products_atom_mapping = products_atom_mapping
Should be easy for these elementary reactions. Yeah, let's leave it for later now.

2020-11-08 21:12 UTC, mjwen commented on pymatgen/reaction_network/reaction.py
> +        #  value. We'd better directly define `num_reactants()`
Deleted.

2020-11-08 21:12 UTC, mjwen commented on pymatgen/reaction_network/reaction.py
> +# TODO rename to IntermolSingleBondChangeReaction, rename argument `product` to `products`
Let's make the changes when moving to the new mrnet repo.

2020-11-08 21:13 UTC, mjwen commented on pymatgen/reaction_network/reaction.py
> +) -> Tuple[bool, Union[None, Dict[int, int]]]:
Yes, it will find A mapping between the nodes.

2020-11-08 21:15 UTC, mjwen commented on pymatgen/reaction_network/reaction.py
> +        return subgraphs
The reason to not reuse MoleculeGraph is that we need the nodes not be reordered. Good call that this should be a function.

2020-11-08 21:16 UTC, mjwen commented on pymatgen/reaction_network/tests/test_reaction.py
> +
Moved this to reaction.py and added a new function `unbucket_mol_entries()` to do the opposite.

2020-11-08 21:26 UTC, mjwen commented on pymatgen/reaction_network/reaction.py
>  class CoordinationBondChangeReaction(Reaction):
Yes, coordinate bond should it be.

2020-11-08 22:34 UTC, merged